### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by darkdarcool** [PyScript-Language/PyScript-Compiler#3]
LOL how do you print? I copied main.py into a repl and made a index.pys file, with the following code:
```
console.print("Hello World!");
```
And then I ran it and gave the file info and it gave this error:
```
Traceback (most recent call last):
  File "main.py", line 264, in CONSOLEprint
    if PASS:
UnboundLocalError: local variable 'PASS' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 438, in <module>
    CONSOLEprint()
  File "main.py", line 271, in CONSOLEprint
    raise InvalidSyntaxError("The 'console.print' statement must have a closing ');!")
__main__.InvalidSyntaxError: The 'console.print' statement must have a closing ');!
```
Am I doing something wrong here?

**Comment by JBYT27** [comment]
Nah, it should probably be an error inside the compiler, I should fix it later on ;) Thanks for finding it for me xD

**Comment by darkdarcool** [comment]
Also an idea is that you should make a pysconfig.json file to have configurations or something. Basically a tscofig.json file

**Comment by JBYT27** [comment]
maybe?

**Comment by darkdarcool** [comment]
I can maybe help with that tho

**Comment by darkdarcool** [comment]
@JBYT27 Does it work now?

**Comment by darkdarcool** [comment]
@JBYT27 K cool
